import SinglyLinkedList as SLL

_list = SLL.SinglyLinkedList()
print("Making empty _list...")
print(_list, "length =",_list.get_length())
_list.append(5)
print("appending 5...")
print(_list, "length =",_list.get_length())
_list.append(4)
_list.extend(_list)
print("appending 4 then extending by self...")
print(_list, "length =",_list.get_length())
_list.insert(0, 3)
print("inserting 3 at index 0")
print(_list, "length =",_list.get_length())
_list.insert(3, 1)
print("inserting 1 at index 3")
print(_list, "length =",_list.get_length())
_list.insert(_list.get_length(), 0)
print("inserting 0 at last index")
print(_list, "length =",_list.get_length())
_list.reverse()
print("reversing _list...")
print(_list, "length =",_list.get_length())
print("popping from _list...", _list.pop())
print(_list, "length =",_list.get_length())
print("popping from front...", _list.pop(0))
print(_list, "length =", _list.get_length())
print("popping from index 3...", _list.pop(3))
print(_list, "length =", _list.get_length())
print("removing 5", _list.remove(5))
print(_list, "length =", _list.get_length())